name: Blank commit every hour

on:
  schedule:
    - cron: "0 * * * *"
  push:
    paths:
      - '**.yml'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Make blank commit and push
      run: |
        git pull origin main
        git commit --allow-empty -m ":3"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
